version: '3.4'
services:
#  db:
#    image: mysql:8.0
#    cap_add:
#      - SYS_NICE
#    restart: always
#    network_mode: host
#    environment:
#      - MYSQL_ROOT_PASSWORD=Test1234
#      - MYSQL_DATABASE=test_zivan
#      - MYSQL_USER=dbuser
#      - MYSQL_PASSWORD=dbuserpassword
#    volumes:
#      - ./dbdata:/var/lib/mysql
#      - ./SqlScripts/setup.sql:/docker-entrypoint-initdb.d/1.sql
  simulationdevices:
#    depends_on:
#       - db
    image: harbor.wolkabout.com/testing/simulationdevices:auth
    network_mode: host
    volumes:
      - ./config/appsettings.json:/app/appsettings.json
